version: 2
updates:
  - package-ecosystem: github-actions
    directory: / # パッケージマニフェスト配置先ディレクトリ。ただしGithub actionのみ固定で"/"
    schedule:
      interval: daily
  # TODO: requirement.txt自動更新PR作成動確の上コメントアウト解除
  # - package-ecosystem: pip
  #   directory: ./
  #   schedule:
  #     interval: daily
