name: Python application
on: push
jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        timeout-minutes: 5  # デフォルトは360分なので、コスト削減を考慮して念の為設定
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version-file: .python-version
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install ruff pytest pytest-cov
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Lint with ruff
              run: |
                ruff check --output-format=github .
            # TODO: テスト作成後にコメントアウト解除
            # - name: Test with pytest
            #   run: |
            #     pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
